# Generated by Django 4.0.3 on 2022-04-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_profile_facebook_remove_profile_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_no',
        ),
    ]
